name: Bump GitHub Tag & Release Versions

on:
  push:
    branches:
      - main

env:
  FETCH_ALL: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and Push Tag
        id: bump_tag_version
        uses: mathieudutour/github-tag-action@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fetch_all_tags: ${{ env.FETCH_ALL }}
      - name: Create a GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.bump_tag_version.outputs.new_tag }}
          name: Release ${{ steps.bump_tag_version.outputs.new_tag }}
          body: ${{ steps.bump_tag_version.outputs.changelog }}