name: Docker Buildx & Push
run-name: docker-buildx-push

on:
  pull_request:
    types: ['closed']
    branches: ['main']
  push:
    branches: ['main']
    paths-ignore: ['**.md']
    tags: ['v*']

env:
  CHECKOUT_FETCH_DEPTH: '0'
  INITIAL_TAG_VERSION: '1.0'
  TAG_BASE_NAME: 'steptimeeditor/na.ddns'

jobs:
  tag_version_bump:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: ${{ env.CHECKOUT_FETCH_DEPTH }}
          ref: ${{ github.event.pull_request.merge_commit_sha }}
      - name: Github Tag Bump
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: ${{ env.INITIAL_TAG_VERSION }}
          WITH_V: true
  docker_buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Docker Metadata
        id: metadata
        uses: docker/metadata-action@v5.0.0
        with:
          images: |
            ${{ env.TAG_BASE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          labels: ${{ steps.metadata.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}